### ISSUE TITLE
Причесать фронтенд

### ISSUE THREAD

**Issue by HPotter** [pythontutor/new-pythontutor-ru#3]
- [ ] вынести js в файлы
- [ ] вынести css в файлы
- [ ] починить или убрать кнопки в меню
- [ ] сделать css для узких экранов и мобильных - `@media` и проч.
- [ ] сделать нормальный футер
- [ ] сделать нормальную левую панель в уроках\задачах
- [ ] сделать список задач в задачах
- [ ] добавить в редактор кода кнопку "отладить" вместо галки "запустить пошагово"
- [ ] переверстать редактор кода полностью
- [ ] сделать колонку текста поуже
- [ ] добавить кнопку удаления сохраненного решения

\+ еще куча TODO разбросано по коду
